require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/fields", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Field. As you add validations to Field, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Field.create! valid_attributes
      get fields_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      field = Field.create! valid_attributes
      get field_url(field)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_field_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      field = Field.create! valid_attributes
      get edit_field_url(field)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Field" do
        expect {
          post fields_url, params: { field: valid_attributes }
        }.to change(Field, :count).by(1)
      end

      it "redirects to the created field" do
        post fields_url, params: { field: valid_attributes }
        expect(response).to redirect_to(field_url(Field.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Field" do
        expect {
          post fields_url, params: { field: invalid_attributes }
        }.to change(Field, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post fields_url, params: { field: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested field" do
        field = Field.create! valid_attributes
        patch field_url(field), params: { field: new_attributes }
        field.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the field" do
        field = Field.create! valid_attributes
        patch field_url(field), params: { field: new_attributes }
        field.reload
        expect(response).to redirect_to(field_url(field))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        field = Field.create! valid_attributes
        patch field_url(field), params: { field: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested field" do
      field = Field.create! valid_attributes
      expect {
        delete field_url(field)
      }.to change(Field, :count).by(-1)
    end

    it "redirects to the fields list" do
      field = Field.create! valid_attributes
      delete field_url(field)
      expect(response).to redirect_to(fields_url)
    end
  end
end
